name: mo3awen_website
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cloud_functions: ^4.1.1
  country_pickers: ^2.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  firebase_database: ^10.0.1
  firebase_storage: ^11.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.1
  google_fonts: ^4.0.3
  html: ^0.15.3
  image_network: ^2.5.2
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/page-1/images/
